apiVersion: 1

datasources:
  - name: Acore Postgres
    type: postgres
    access: proxy
    url: ${PG_HOST}:${PG_HOST_PORT}
    database: ${PG_NAME}
    user: ${PG_USER}
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: ${PG_SSL_MODE}
